### ISSUE TITLE
BHSD DataSets

### ISSUE THREAD

**Issue by simi-chen** [White65534/BHSD#1]
Is the BHSD dataset available for public access? If so, could you please provide a download link? Thank you

**Comment by steve-zeyu-zhang** [comment]
Hi simi-chen,

The dataset is currently under review by Kaggle, you can follow it up on the Kaggle website.

Team BHSD

**Comment by YazdanSalimi** [comment]
Hello,
Congratulations on a valuable study.
The dataset is not available on the Kaggle website either.
Will you share the model to compare?
Thank you

**Comment by peterant1995** [comment]
Hi,
Thanks for your contribution to this study. However, the dataset seems still unavailable in Kaagle. Do you have any idea what's going on and when can we actually download the dataset? 
Thank you.

**Comment by thangngoc89** [comment]
Hi @steve-zeyu-zhang ,

Are there any follow up on this? The data still isn't available on Kaggle. Did you consider uploading to another places like [zenodo.org](https://zenodo.org)? Thank you very much

**Comment by steve-zeyu-zhang** [comment]
Hi,

The dataset is available on Kaggle.

Please try again and let me know if the problem still remains.

The issue will be closed for now.

Team BHSD

**Comment by YazdanSalimi** [comment]
Thank you for updating the link, the files are niigz NIFTI format, but still it seems the slicing information is not uniform, Could you please check one of the images and update them if neccessary? I am using ITKSNAP for opening.
Thank you
