### ISSUE TITLE
Official split and missing case

### ISSUE THREAD

**Issue by thangngoc89** [White65534/BHSD#3]
Could you provide the official split for 96 training and 96 testing sequences? 

Also, in the dataset on Kaggle, there are only 191 cases instead of 192 cases in the paper.

**Comment by steve-zeyu-zhang** [comment]
For the official train-test split and label of each semantic used in the paper, see [dataset.json](https://github.com/White65534/BHSD/blob/main/dataset.json).

For datasets, see newest updates.
