### ISSUE TITLE
what pixel level in seg represents?

### ISSUE THREAD

**Issue by CosmoWood** [White65534/BHSD#4]
pixel 1 to 5 represents which kind of hemorrhage?

**Comment by steve-zeyu-zhang** [comment]
For the official train-test split and label of each semantic used in the paper, see [dataset.json](https://github.com/White65534/BHSD/blob/main/dataset.json).

**Comment by steve-zeyu-zhang** [comment]
For the official train-test split and label of each semantic used in the paper, see [dataset.json](https://github.com/White65534/BHSD/blob/main/dataset.json).
