### ISSUE TITLE
only see 191 files without format suffix, in stead of 192, and how properly load/ read them without format info

### ISSUE THREAD

**Issue by samleoqh** [White65534/BHSD#5]
Hi, 
Thanks for open source the great dataset.  As said in your paper, there should be 192 CT scans, but only 191 files were released on Kaggle, and also no format suffix indicates what format these files are, I guess it would be nii, or nii.gz ?, shall the uses need to rename these files with proper suffix in order to read them with such as ITK-SNAP viewer? However I tried to add suffix of both .nii and .nii.gz, but still couldn't read them with ITK-SNAP? Please advise their correct format to read/load them properly？

Thanks again.

**Comment by steve-zeyu-zhang** [comment]
For the official train-test split and label of each semantic used in the paper, see [dataset.json](https://github.com/White65534/BHSD/blob/main/dataset.json).

For datasets, see newest updates.
