### ISSUE TITLE
Empy GT

### ISSUE THREAD

**Issue by smcch** [White65534/BHSD#9]
Hello !

I have downloaded the dataset from https://www.kaggle.com/datasets/stevezeyuzhang/bhsd-dataset and renamed the files by adding the .nii.gz extension. I can display the images correctly, however, the segmentations are empty. Attached is an example. Could you please help me?

Thanks
[ID_10c64d22_ID_4c9aad31ca.nii.gz](https://github.com/White65534/BHSD/files/15251344/ID_10c64d22_ID_4c9aad31ca.nii.gz)

**Comment by Destinycjk** [comment]
I have the same problem, and do you have a solution to it?

**Comment by White65534** [comment]
https://huggingface.co/datasets/WuBiao/BHSD

We are preparing for the competition organized by MICCAI and the data has been transferred to huggingface.

**Comment by smcch** [comment]
Thanks!

**Comment by steve-zeyu-zhang** [comment]
Addressed. Please check the latest dataset.
